// Generated by CIRCT firtool-1.62.0
module Alu(
  input  [2:0]  io_i_uop,
  input         io_i_signed,
  input  [31:0] io_i_s1,
                io_i_s2,
  output [31:0] io_o_res
);

  wire [62:0]      _io_o_res_T_4 = {31'h0, io_i_s1} << io_i_s2[4:0];
  wire [31:0]      _GEN = {27'h0, io_i_s2[4:0]};
  wire [7:0][31:0] _GEN_0 =
    {{io_i_s1 & io_i_s2},
     {io_i_s1 | io_i_s2},
     {io_i_signed ? $signed($signed(io_i_s1) >>> _GEN) : io_i_s1 >> _GEN},
     {io_i_s1 ^ io_i_s2},
     {32'h0},
     {{31'h0, io_i_signed ? $signed(io_i_s1) < $signed(io_i_s2) : io_i_s1 < io_i_s2}},
     {_io_o_res_T_4[31:0]},
     {io_i_signed ? io_i_s1 - io_i_s2 : io_i_s1 + io_i_s2}};
  assign io_o_res = _GEN_0[io_i_uop];
endmodule

