// Generated by CIRCT firtool-1.62.0
module Bru(
  input  [2:0]  io_i_uop,
  input  [15:0] io_i_pc,
  input  [31:0] io_i_s1,
                io_i_s2,
  output        io_o_br,
  output [31:0] io_o_res
);

  wire       _GEN = (&io_i_uop) & io_i_s1 >= io_i_s2;
  wire [7:0] _GEN_0 =
    {{_GEN},
     {io_i_s1 < io_i_s2},
     {$signed(io_i_s1) >= $signed(io_i_s2)},
     {$signed(io_i_s1) < $signed(io_i_s2)},
     {_GEN},
     {_GEN},
     {io_i_s1 != io_i_s2},
     {io_i_s1 == io_i_s2}};
  assign io_o_br = io_i_uop == 3'h2 | _GEN_0[io_i_uop];
  assign io_o_res = {16'h0, io_i_pc + 16'h4};
endmodule

