// Generated by CIRCT firtool-1.62.0
module Ram(
  input         clock,
                reset,
                io_b_port_valid,
  input  [4:0]  io_b_port_addr,
  input  [3:0]  io_b_port_wen,
  input  [31:0] io_b_port_wdata,
  output [31:0] io_b_port_rdata
);

  RamSv #(
    .INIT_FILE("sw.ram.mem"),
    .N_DATA(32),
    .N_DATA_BYTE(4)
  ) m_ram (
    .i_clock (clock),
    .i_reset (reset),
    .i_en    (io_b_port_valid),
    .i_addr  (io_b_port_addr),
    .i_wen   (io_b_port_wen),
    .i_wdata (io_b_port_wdata),
    .o_rdata (io_b_port_rdata)
  );
endmodule

