// Generated by CIRCT firtool-1.62.0
module Sys(
  input        clock,
               reset,
               io_i_boot,
  output [7:0] io_b_gpio_eno,
  input  [7:0] io_b_gpio_in,
  output [7:0] io_b_gpio_out,
  input        io_b_uart_rx,
  output       io_b_uart_tx
);

  wire        _m_bootloader_io_o_valid;
  wire [7:0]  _m_bootloader_io_o_data;
  wire        _m_bootloader_io_o_bl;
  wire        _m_bootloader_io_b_mem_valid;
  wire [15:0] _m_bootloader_io_b_mem_addr;
  wire [3:0]  _m_bootloader_io_b_mem_wen;
  wire [31:0] _m_bootloader_io_b_mem_wdata;
  wire [31:0] _m_uart_io_b_mem_rdata;
  wire        _m_uart_io_o_bl_ready;
  wire        _m_uart_io_o_bl_valid;
  wire [7:0]  _m_uart_io_o_bl_data;
  wire [31:0] _m_gpio8_io_b_mem_rdata;
  wire [31:0] _m_ram_io_b_port_rdata;
  wire        _m_core_io_b_mem_valid;
  wire [15:0] _m_core_io_b_mem_addr;
  wire [3:0]  _m_core_io_b_mem_wen;
  wire [31:0] _m_core_io_b_mem_wdata;
  reg         r_valid;
  reg  [31:0] r_addr;
  wire        _GEN = _m_bootloader_io_b_mem_addr < 16'h80;
  wire [6:0]  _m_ram_io_b_port_wen_T_1 =
    {3'h0, _m_bootloader_io_b_mem_wen} << _m_bootloader_io_b_mem_addr[1:0];
  wire [62:0] _m_ram_io_b_port_wdata_T_2 =
    {31'h0, _m_bootloader_io_b_mem_wdata}
    << {58'h0, _m_bootloader_io_b_mem_addr[1:0], 3'h0};
  wire        _GEN_0 =
    (|(_m_bootloader_io_b_mem_addr[15:11])) & _m_bootloader_io_b_mem_addr < 16'h840;
  wire        _GEN_1 =
    _m_bootloader_io_b_mem_addr > 16'h83F & _m_bootloader_io_b_mem_addr < 16'h880;
  wire        _GEN_2 = _GEN | _GEN_0;
  wire        _GEN_3 = _m_bootloader_io_o_bl & (_GEN_2 | _GEN_1);
  wire [31:0] _GEN_4 =
    _GEN
      ? _m_ram_io_b_port_rdata
      : _GEN_0 ? _m_gpio8_io_b_mem_rdata : _m_uart_io_b_mem_rdata;
  wire        _GEN_5 = _m_core_io_b_mem_addr < 16'h80;
  wire [6:0]  _m_ram_io_b_port_wen_T_3 =
    {3'h0, _m_core_io_b_mem_wen} << _m_core_io_b_mem_addr[1:0];
  wire [62:0] _m_ram_io_b_port_wdata_T_5 =
    {31'h0, _m_core_io_b_mem_wdata} << {58'h0, _m_core_io_b_mem_addr[1:0], 3'h0};
  wire        _GEN_6 =
    (|(_m_core_io_b_mem_addr[15:11])) & _m_core_io_b_mem_addr < 16'h840;
  wire [3:0]  _GEN_7 =
    _m_bootloader_io_o_bl ? _m_bootloader_io_b_mem_wen : _m_core_io_b_mem_wen;
  wire [31:0] _GEN_8 =
    _m_bootloader_io_o_bl ? _m_bootloader_io_b_mem_wdata : _m_core_io_b_mem_wdata;
  wire [31:0] _GEN_9 =
    _GEN_5
      ? _m_ram_io_b_port_rdata
      : _GEN_6 ? _m_gpio8_io_b_mem_rdata : _m_uart_io_b_mem_rdata;
  wire        _GEN_10 = r_addr < 32'h80;
  wire [31:0] _GEN_11 = {27'h0, r_addr[1:0], 3'h0};
  wire        _GEN_12 = (|(r_addr[31:11])) & r_addr < 32'h840;
  wire        _GEN_13 = r_addr > 32'h83F & r_addr < 32'h880;
  always @(posedge clock) begin
    if (reset)
      r_valid <= 1'h0;
    else
      r_valid <=
        ~r_valid
        & (_m_bootloader_io_o_bl
             ? _m_bootloader_io_b_mem_valid & _GEN_3
             : _m_core_io_b_mem_valid);
    if (r_valid) begin
    end
    else
      r_addr <=
        {16'h0,
         _m_bootloader_io_o_bl ? _m_bootloader_io_b_mem_addr : _m_core_io_b_mem_addr};
  end // always @(posedge)
  Core m_core (
    .clock          (clock),
    .reset          (reset),
    .io_i_bl        (_m_bootloader_io_o_bl),
    .io_b_mem_valid (_m_core_io_b_mem_valid),
    .io_b_mem_addr  (_m_core_io_b_mem_addr),
    .io_b_mem_wen   (_m_core_io_b_mem_wen),
    .io_b_mem_wdata (_m_core_io_b_mem_wdata),
    .io_b_mem_rdata
      (r_valid
         ? (_GEN_10
              ? _m_ram_io_b_port_rdata >> _GEN_11
              : _GEN_12
                  ? _m_gpio8_io_b_mem_rdata
                  : _GEN_13 ? _m_uart_io_b_mem_rdata : _GEN_9)
         : _GEN_9)
  );
  Ram m_ram (
    .clock           (clock),
    .reset           (reset),
    .io_b_port_valid
      (_m_bootloader_io_o_bl
         ? _GEN & _m_bootloader_io_b_mem_valid
         : _GEN_5 & _m_core_io_b_mem_valid),
    .io_b_port_addr
      (_m_bootloader_io_o_bl
         ? _m_bootloader_io_b_mem_addr[6:2]
         : _m_core_io_b_mem_addr[6:2]),
    .io_b_port_wen
      (_m_bootloader_io_o_bl
         ? _m_ram_io_b_port_wen_T_1[3:0]
         : _m_ram_io_b_port_wen_T_3[3:0]),
    .io_b_port_wdata
      (_m_bootloader_io_o_bl
         ? _m_ram_io_b_port_wdata_T_2[31:0]
         : _m_ram_io_b_port_wdata_T_5[31:0]),
    .io_b_port_rdata (_m_ram_io_b_port_rdata)
  );
  Gpio8 m_gpio8 (
    .clock          (clock),
    .reset          (reset),
    .io_b_mem_valid
      (_m_bootloader_io_o_bl
         ? ~_GEN & _GEN_0 & _m_bootloader_io_b_mem_valid
         : ~_GEN_5 & _GEN_6 & _m_core_io_b_mem_valid),
    .io_b_mem_addr
      (_m_bootloader_io_o_bl
         ? _m_bootloader_io_b_mem_addr[3:0]
         : _m_core_io_b_mem_addr[3:0]),
    .io_b_mem_wen   (_GEN_7),
    .io_b_mem_wdata (_GEN_8),
    .io_b_mem_rdata (_m_gpio8_io_b_mem_rdata),
    .io_b_gpio_eno  (io_b_gpio_eno),
    .io_b_gpio_in   (io_b_gpio_in),
    .io_b_gpio_out  (io_b_gpio_out)
  );
  Uart m_uart (
    .clock          (clock),
    .reset          (reset),
    .io_i_bl        (_m_bootloader_io_o_bl),
    .io_b_mem_valid
      (_m_bootloader_io_o_bl
         ? ~_GEN_2 & _GEN_1 & _m_bootloader_io_b_mem_valid
         : ~(_GEN_5 | _GEN_6) & _m_core_io_b_mem_addr > 16'h83F
           & _m_core_io_b_mem_addr < 16'h880 & _m_core_io_b_mem_valid),
    .io_b_mem_addr
      (_m_bootloader_io_o_bl
         ? _m_bootloader_io_b_mem_addr[4:0]
         : _m_core_io_b_mem_addr[4:0]),
    .io_b_mem_wen   (_GEN_7),
    .io_b_mem_wdata (_GEN_8),
    .io_b_mem_rdata (_m_uart_io_b_mem_rdata),
    .io_o_bl_ready  (_m_uart_io_o_bl_ready),
    .io_i_bl_valid  (_m_bootloader_io_o_valid),
    .io_i_bl_data   (_m_bootloader_io_o_data),
    .io_o_bl_valid  (_m_uart_io_o_bl_valid),
    .io_o_bl_data   (_m_uart_io_o_bl_data),
    .io_b_uart_rx   (io_b_uart_rx),
    .io_b_uart_tx   (io_b_uart_tx)
  );
  Bootloader m_bootloader (
    .clock          (clock),
    .reset          (reset),
    .io_i_boot      (io_i_boot),
    .io_i_valid     (_m_uart_io_o_bl_valid),
    .io_i_data      (_m_uart_io_o_bl_data),
    .io_i_ready     (_m_uart_io_o_bl_ready),
    .io_o_valid     (_m_bootloader_io_o_valid),
    .io_o_data      (_m_bootloader_io_o_data),
    .io_o_bl        (_m_bootloader_io_o_bl),
    .io_b_mem_valid (_m_bootloader_io_b_mem_valid),
    .io_b_mem_addr  (_m_bootloader_io_b_mem_addr),
    .io_b_mem_wen   (_m_bootloader_io_b_mem_wen),
    .io_b_mem_wdata (_m_bootloader_io_b_mem_wdata),
    .io_b_mem_ready (_GEN_3),
    .io_b_mem_rdata
      (r_valid
         ? (_GEN_10
              ? _m_ram_io_b_port_rdata >> _GEN_11
              : _GEN_12
                  ? _m_gpio8_io_b_mem_rdata
                  : _GEN_13 ? _m_uart_io_b_mem_rdata : _GEN_4)
         : _GEN_4)
  );
endmodule

